spring:
  jpa:
    open-in-view: false
  application:
    admin:
      enabled: true
  boot:
    admin:
      client:
        url: http://localhost:${server.port}
        instance:
          service-base-url: http://localhost:${server.port}
  main:
    banner-mode: 'off'
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: info
    com.zaxxer.hikari: error

